POST http://localhost:3000/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "username": "katamsaamam",
    "email": "sasas@gmail.com",
    "password": "password"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "username": "katamsaamam",
    "password": "password"
}















###
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "katamsaamam",
    "password": "password"
}

###
GET  http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJEaWRpbiIsInBhc3N3b3JkIjoiJDJiJDEwJENBLjJENjhZcUI2T1dJb1Zodjk4ZE9HYU5yRUNWckJDWEJLUHZWZDl4MXpxeVF1ckZyQVVtIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTY4NjI1MDN9.HkQzo1RJLexobfGhjWcyA8SVcAq5Mh6IEcwwN9-kk00

###
PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJEaWRpbiIsInBhc3N3b3JkIjoiJDJiJDEwJENBLjJENjhZcUI2T1dJb1Zodjk4ZE9HYU5yRUNWckJDWEJLUHZWZDl4MXpxeVF1ckZyQVVtIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTY4NjI1MDN9.HkQzo1RJLexobfGhjWcyA8SVcAq5Mh6IEcwwN9-kk00

{
    "fullName": "password2",
    "username": "kaka",
    "password": "passwordxxx"
}


###
PATCH http://localhost:3000/api/users/current/student
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJEaWRpbiIsInBhc3N3b3JkIjoiJDJiJDEwJENBLjJENjhZcUI2T1dJb1Zodjk4ZE9HYU5yRUNWckJDWEJLUHZWZDl4MXpxeVF1ckZyQVVtIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTY4NjI1MDN9.HkQzo1RJLexobfGhjWcyA8SVcAq5Mh6IEcwwN9-kk00

{
    "nis": "141212",
    "grade": "10"
}

###
PATCH http://localhost:3000/api/users/current/teacher
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJrYXRhbWFtYW0iLCJwYXNzd29yZCI6IiQyYiQxMCQ3UGpPd3lQeWhHMXBkd3JWMFNCY2NlZEIyU1hvWlZhUXEyTFkyYnZKNHV2Z3lpV3lNSk5rZSIsInJvbGUiOiJURUFDSEVSIiwiaWF0IjoxNzU2ODcwODg0fQ.tAQKkMKmz3vK7yGZ1a27DzLw3x2C-QruPeuaWW0R5dY

{
    "nip": "13141"
}